class Exception1{
	public static void main(String[] args) {
		try{
          int a[]={1,2,3,4,5,6,7,8,9};
			System.out.println(a[1]);
		} catch (Exception e) {
            System.out.println("something went wrong");
	    	}
		}
	}